function writeToDisk( fid, prompt, early, late, codeFilt, carrFilt, cnoValue )

% just print the data to file ...

for ii = 1:length( prompt.buffer ),
    fprintf( fid, '%g %g %g %g %g %g %g %g %g \n', ...
                                             real(prompt.buffer( ii )), imag(prompt.buffer( ii )), ...
                                             real(early.buffer( ii )), imag(early.buffer( ii )), ...
                                             real(late.buffer( ii )), imag(late.buffer( ii )), ...
                                             codeFilt.buffer( ii ), ...
                                             carrFilt.buffer( ii ), ...
                                             cnoValue.buffer( ii ) );
end